CREATE TABLE tasks(
    id INTEGER PRIMARY KEY AUTO_INCREMENT,
    title VARCHAR(200) NOT NULL,
    description VARCHAR(300),
    status BOOLEAN NOT NULL DEFAULT 0,
    createAt TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
);

CREATE TABLE users(
    id INTEGER PRIMARY KEY AUTO_INCREMENT,
    user VARCHAR(200) UNIQUE NOT NULL,
    password VARCHAR(255) NOT NULL,
    email VARCHAR(300) UNIQUE NOT NULL,
    createAt TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
);